name: pyfinch
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib
  - numpy
  - pandas
  - pip
  - scikit-learn
  - scipy
  - seaborn
  - librosa
  - scikit-posthocs
  - statsmodels
  - pip:
      - soundfile
