"""
load data (from .rhd, .txt, .wav, etc)
"""


def read_spk_txt(spk_txt_file, *unit_nb, unit='second'):
    """
    Read the output .txt from the Offline Sorter
    Column header of the input .txt
    ['Channel', 'Unit', 'Timestamp']
    Disregard the first column since it is always 1
    Column 3 to 35 stores waveforms
    """
    import numpy as np

    spk_info = np.loadtxt(spk_txt_file, delimiter='\t', skiprows=1)  # skip header

    '''select only the unit (there could be multiple isolated units in the same file)'''
    if unit_nb:  # if the unit number is specified
        spk_info = spk_info[spk_info[:, 1] == unit_nb, :]

    spk_ts = spk_info[:, 2]  # analysis time stamps
    spk_waveform = spk_info[:, 3:]  # analysis waveform
    nb_spk = spk_waveform.shape[0]  # total number of spikes

    # units are in second by default, but convert to  millisecond with the argument
    if unit == 'ms':
        spk_ts *= 1E3

    return spk_ts, spk_waveform, nb_spk


def read_rhd(filename):
    """
    Reads Intan Technologies RHD2000 data file generated by evaluation board GUI.
    Data are returned in a dictionary, for future extensibility.
    """
    from load_intan_rhd_format.load_intan_rhd_format import read_rhd
    intan = read_rhd(filename)
    return intan

